import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import ReactQueryProvider from './_providers/react-query-provider';
import RecoilRootProvider from './_providers/recoil-root-provider';
import Providers from './_providers/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
